#!/bin/tcsh

#SBATCH --job-name="compute_crps"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=compute_crps_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment01"

set evaluation_dir_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_100x5/validation_20200102-20200115"

set REGIME_STRINGS_DASHED=("no-cloud" "single-layer-cloud" "multi-layer-cloud")
set REGIME_STRINGS_UNDERSCORED=("no_cloud" "single_layer_cloud" "multi_layer_cloud")

set i=1

while ($i <= ${#REGIME_STRINGS_DASHED})
    set regime_string_dashed=${REGIME_STRINGS_DASHED[$i]}
    set regime_string_underscored=${REGIME_STRINGS_UNDERSCORED[$i]}
    
    set prediction_file_name="${evaluation_dir_name}/by_cloud_regime/predictions_${regime_string_dashed}.nc"
    set output_file_name="${evaluation_dir_name}/by_cloud_regime/${regime_string_underscored}/crps.nc"
    
    python3 -u "${CODE_DIR_NAME}/compute_crps.py" \
    --input_prediction_file_name="${prediction_file_name}" \
    --num_integration_levels=1000 \
    --ensemble_size_for_climo=500 \
    --output_file_name="${output_file_name}"
    
    @ i = $i + 1
end
