#!/bin/tcsh

#SBATCH --job-name="evaluate_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=18:00:00
#SBATCH --array=1-63
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_uq_experiment01"

set FIRST_LAYER_CHANNEL_COUNTS=("032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096")
set UQ_METHOD_STRINGS=("mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps")
set DENSE_LAYER_DROPOUT_RATES=("0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50")

set num_first_layer_channels=${FIRST_LAYER_CHANNEL_COUNTS[$SLURM_ARRAY_TASK_ID]}
set uq_method_string=${UQ_METHOD_STRINGS[$SLURM_ARRAY_TASK_ID]}
set dense_layer_dropout_rate=${DENSE_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/${uq_method_string}_num-first-layer-channels=${num_first_layer_channels}_dense-layer-dropout-rate=${dense_layer_dropout_rate}/model"
echo $model_dir_name

set evaluation_dir_name="${model_dir_name}/validation_20200102-20200115_20200102-20200115"

set REGIME_STRINGS_DASHED=("no-cloud" "single-layer-cloud" "multi-layer-cloud")
set REGIME_STRINGS_UNDERSCORED=("no_cloud" "single_layer_cloud" "multi_layer_cloud")

set i=1

while ($i <= ${#REGIME_STRINGS_DASHED})
    set regime_string_dashed=${REGIME_STRINGS_DASHED[$i]}
    set regime_string_underscored=${REGIME_STRINGS_UNDERSCORED[$i]}
    
    set prediction_file_name="${evaluation_dir_name}/by_cloud_regime/predictions_${regime_string_dashed}.nc"
    set evaluation_dir_name="${evaluation_dir_name}/by_cloud_regime/${regime_string_underscored}"
    
    python3 -u "${CODE_DIR_NAME}/evaluate_neural_net.py" \
    --input_prediction_file_name="${prediction_file_name}" \
    --num_bootstrap_reps=1 \
    --num_heating_rate_bins=41 \
    --heating_rate_limits_k_day01 0 41 \
    --num_raw_flux_bins=50 \
    --raw_flux_limits_w_m02 0 1250 \
    --num_net_flux_bins=41 \
    --net_flux_limits_w_m02 -1050 1000 \
    --output_dir_name="${evaluation_dir_name}"
    
    @ i = $i + 1
end
