#!/bin/tcsh

#SBATCH --job-name="compute_spread_vs_skill"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --array=1-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=compute_spread_vs_skill_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment01"

set PATHLESS_INPUT_FILE_NAMES=("predictions_part01.nc" "predictions_part02.nc" "predictions_part03.nc" "predictions_part04.nc" "predictions_part05.nc" "predictions_part06.nc" "predictions_part07.nc" "predictions_part08.nc" "predictions_part09.nc")
set PATHLESS_OUTPUT_FILE_NAMES=("spread_vs_skill_part01.nc" "spread_vs_skill_part02.nc" "spread_vs_skill_part03.nc" "spread_vs_skill_part04.nc" "spread_vs_skill_part05.nc" "spread_vs_skill_part06.nc" "spread_vs_skill_part07.nc" "spread_vs_skill_part08.nc" "spread_vs_skill_part09.nc")

set prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_100x5/validation/${PATHLESS_INPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"
set output_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_100x5/validation/${PATHLESS_OUTPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/compute_spread_vs_skill.py" \
--input_prediction_file_name="${prediction_file_name}" \
--num_heating_rate_bins=100 \
--heating_rate_limits_k_day01 0 2 \
--num_raw_flux_bins=100 \
--raw_flux_limits_w_m02 0 150 \
--num_net_flux_bins=100 \
--net_flux_limits_w_m02 0 150 \
--output_file_name="${output_file_name}"
