#!/bin/bash

#SBATCH --job-name="evaluate_by_cloud_regime"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --array=0-5
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_cloud_regime_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/spectral_experiment04_reverse_ablation"

USE_RESIDUAL_FLAGS=("0" "1" "0" "1" "0" "1")
LOSS_TYPE_STRINGS=("simple" "simple" "intermediate" "intermediate" "complicated" "complicated")

use_residual_flag=${USE_RESIDUAL_FLAGS[$SLURM_ARRAY_TASK_ID]}
loss_type_string=${LOSS_TYPE_STRINGS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/use-residual-blocks=${use_residual_flag}_loss-type=${loss_type_string}"
validation_dir_name="${model_dir_name}/validation"

REGIME_STRINGS_DASHED=("no-cloud" "single-layer-cloud" "multi-layer-cloud")
REGIME_STRINGS_UNDERSCORED=("no_cloud" "single_layer_cloud" "multi_layer_cloud")
i=0

while [ $i -lt ${#REGIME_STRINGS_DASHED[@]} ]; do
    regime_string_dashed=${REGIME_STRINGS_DASHED[$i]}
    regime_string_underscored=${REGIME_STRINGS_UNDERSCORED[$i]}
    
    prediction_file_name="${validation_dir_name}/by_cloud_regime/${regime_string_underscored}/predictions.nc"
    evaluation_dir_name="${validation_dir_name}/by_cloud_regime/${regime_string_underscored}"
    
    python3 -u "${CODE_DIR_NAME}/evaluate_neural_net.py" \
    --input_prediction_file_name="${prediction_file_name}" \
    --num_bootstrap_reps=1 \
    --num_heating_rate_bins=41 \
    --heating_rate_limits_k_day01 0 41 \
    --num_raw_flux_bins=50 \
    --raw_flux_limits_w_m02 0 1250 \
    --num_net_flux_bins=41 \
    --net_flux_limits_w_m02 -1050 1000 \
    --output_dir_name="${evaluation_dir_name}"
    
    i=$(( $i + 1 ))
done
