#!/bin/tcsh

#SBATCH --job-name="merge_pit_histograms"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=merge_pit_histograms_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_crps_experiment01"

set PATHLESS_INPUT_FILE_NAMES=("pit_histograms_part01.nc" "pit_histograms_part02.nc" "pit_histograms_part03.nc" "pit_histograms_part04.nc" "pit_histograms_part05.nc" "pit_histograms_part06.nc" "pit_histograms_part07.nc" "pit_histograms_part08.nc" "pit_histograms_part09.nc")

set REGIME_STRINGS=("no_cloud" "single_layer_cloud" "multi_layer_cloud")
set i=1

while ($i <= ${#REGIME_STRINGS})
    set input_file_names_string=""
    set j=1
    
    while ($j <= ${#PATHLESS_INPUT_FILE_NAMES})
        set input_file_names_string="${input_file_names_string} ${TOP_MODEL_DIR_NAME}/model/isotonic_regression/validation_perturbed_for_uq/by_cloud_regime/${REGIME_STRINGS[$i]}/${PATHLESS_INPUT_FILE_NAMES[$j]}"
        
        @ j = $j + 1
    end

    set output_file_name="${TOP_MODEL_DIR_NAME}/model/isotonic_regression/validation_perturbed_for_uq/by_cloud_regime/${REGIME_STRINGS[$i]}/pit_histograms.nc"
    
    python3 -u "${CODE_DIR_NAME}/merge_pit_histograms_over_examples.py" \
    --input_file_names ${input_file_names_string} \
    --output_file_name="${output_file_name}"
    
    @ i = $i + 1
end
