#!/bin/tcsh

#SBATCH --job-name="train_neural_net"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=24:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=train_neural_net_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TEMPLATE_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/u-net++_test/template/model_template.h5"
set OUTPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/u-net++_test"

set TRAINING_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/examples/non_tropical_sites"
set VALIDATION_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/examples/non_tropical_sites"
set NORMALIZATION_FILE_NAME="${TRAINING_DIR_NAME}/learning_examples_20170101-20181224.nc"

python3 -u "${CODE_DIR_NAME}/train_neural_net.py" \
--net_type_string="u_net" \
--input_training_dir_name="${TRAINING_DIR_NAME}" \
--input_validation_dir_name="${VALIDATION_DIR_NAME}" \
--input_normalization_file_name="${NORMALIZATION_FILE_NAME}" \
--input_model_file_name="${TEMPLATE_FILE_NAME}" \
--output_model_dir_name="${OUTPUT_DIR_NAME}" \
--use_generator_for_training=0 \
--use_generator_for_validn=0 \
--target_names "shortwave_heating_rate_k_day01" "shortwave_surface_down_flux_w_m02" "shortwave_toa_up_flux_w_m02" \
--heights_m_agl 10 20 40 60 80 100 120 140 160 180 200 225 250 275 300 350 400 450 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000 4200 4400 4600 4800 5000 5500 6000 6500 7000 8000 9000 10000 11000 12000 13000 14000 15000 18000 20000 22000 24000 27000 30000 33000 36000 39000 42000 46000 50000 \
--omit_heating_rate=0 \
--vector_target_norm_type_string='' \
--scalar_target_norm_type_string='minmax' \
--scalar_target_min_norm_value=0 \
--scalar_target_max_norm_value=1 \
--num_examples_per_batch=256 \
--plateau_lr_multiplier=0.6
