#!/bin/bash

#SBATCH --job-name="plot_spread_vs_skill"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_spread_vs_skill_%A.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_crps_experiment01"

input_file_name="${TOP_MODEL_DIR_NAME}/model/validation_perturbed_for_uq/spread_vs_skill.nc"
output_dir_name="${TOP_MODEL_DIR_NAME}/model/validation_perturbed_for_uq/spread_vs_skill"

python3 -u "${CODE_DIR_NAME}/plot_spread_vs_skill.py" \
--input_file_name="${input_file_name}" \
--plot_inset=0 \
--output_dir_name="${output_dir_name}"
