#!/bin/tcsh

#SBATCH --job-name="plot_examples"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --array=1-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_examples_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_INPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/shortwave_examples_600days/orig_heights"

set PATHLESS_INPUT_FILE_NAMES=("testing_perturbed_for_uq/learning_examples_2020_part01.nc" "testing_perturbed_for_uq/learning_examples_2020_part02.nc" "testing_perturbed_for_uq/learning_examples_2020_part03.nc" "testing_perturbed_for_uq/learning_examples_2020_part04.nc" "testing_perturbed_for_uq/learning_examples_2020_part05.nc" "testing_perturbed_for_uq/learning_examples_2020_part06.nc" "testing_perturbed_for_uq/learning_examples_2020_part07.nc" "testing_perturbed_for_uq/learning_examples_2020_part08.nc" "testing_perturbed_for_uq/learning_examples_2020_part09.nc")
set PATHLESS_OUTPUT_DIR_NAMES=("testing_perturbed_for_uq/learning_examples_2020_part01_plots" "testing_perturbed_for_uq/learning_examples_2020_part02_plots" "testing_perturbed_for_uq/learning_examples_2020_part03_plots" "testing_perturbed_for_uq/learning_examples_2020_part04_plots" "testing_perturbed_for_uq/learning_examples_2020_part05_plots" "testing_perturbed_for_uq/learning_examples_2020_part06_plots" "testing_perturbed_for_uq/learning_examples_2020_part07_plots" "testing_perturbed_for_uq/learning_examples_2020_part08_plots" "testing_perturbed_for_uq/learning_examples_2020_part09_plots")

set input_file_name="${TOP_INPUT_DIR_NAME}/${PATHLESS_INPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"
set output_dir_name="${TOP_INPUT_DIR_NAME}/${PATHLESS_OUTPUT_DIR_NAMES[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/plot_examples.py" \
--input_example_file_name="${input_file_name}" \
--num_examples=50 \
--use_log_scale=1 \
--plot_shortwave=1 \
--output_dir_name="${output_dir_name}"
