#!/bin/tcsh

#SBATCH --job-name="apply_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --array=1-100%50
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment02"
set EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/shortwave_examples_600days/orig_heights/normalized_with_perturbed_training_data/validation_all_perturbed_for_uq"

set ENSEMBLE_MEMBER_INDICES=("001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012" "013" "014" "015" "016" "017" "018" "019" "020" "021" "022" "023" "024" "025" "026" "027" "028" "029" "030" "031" "032" "033" "034" "035" "036" "037" "038" "039" "040" "041" "042" "043" "044" "045" "046" "047" "048" "049" "050" "051" "052" "053" "054" "055" "056" "057" "058" "059" "060" "061" "062" "063" "064" "065" "066" "067" "068" "069" "070" "071" "072" "073" "074" "075" "076" "077" "078" "079" "080" "081" "082" "083" "084" "085" "086" "087" "088" "089" "090" "091" "092" "093" "094" "095" "096" "097" "098" "099" "100")
set ensemble_member_index=${ENSEMBLE_MEMBER_INDICES[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/ensemble-member=${ensemble_member_index}/model"
set model_file_name="${TOP_MODEL_DIR_NAME}/ensemble-member=${ensemble_member_index}/model.h5"

set FIRST_EVAL_TIME_STRINGS=("2020-01-02-000000" "2020-02-12-000000" "2020-03-24-000000" "2020-05-05-000000" "2020-06-16-000000" "2020-07-27-000000" "2020-09-06-000000" "2020-10-19-000000" "2020-11-30-000000")
set LAST_EVAL_TIME_STRINGS=("2020-01-15-235959" "2020-02-25-235959" "2020-04-06-235959" "2020-05-18-235959" "2020-06-29-235959" "2020-08-09-235959" "2020-09-19-235959" "2020-11-02-235959" "2020-12-13-235959")
set PATHLESS_OUTPUT_FILE_NAMES=("predictions_part01.nc" "predictions_part02.nc" "predictions_part03.nc" "predictions_part04.nc" "predictions_part05.nc" "predictions_part06.nc" "predictions_part07.nc" "predictions_part08.nc" "predictions_part09.nc")

set i=1

while ($i <= ${#FIRST_EVAL_TIME_STRINGS})
    set first_eval_time_string=${FIRST_EVAL_TIME_STRINGS[$i]}
    set last_eval_time_string=${LAST_EVAL_TIME_STRINGS[$i]}
    set prediction_file_name="${model_dir_name}/validation_perturbed_for_uq/${PATHLESS_OUTPUT_FILE_NAMES[$i]}"
    
    python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
    --input_model_file_name="${model_file_name}" \
    --input_example_dir_name="${EXAMPLE_DIR_NAME}" \
    --first_time_string="${first_eval_time_string}" \
    --last_time_string="${last_eval_time_string}" \
    --num_dropout_iterations=-1 \
    --max_ensemble_size=200 \
    --output_file_name="${prediction_file_name}"
    
    @ i = $i + 1
end
