#!/bin/tcsh

#SBATCH --job-name="explore_full_and_subset_data"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --array=1-2
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=explore_full_and_subset_data_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_DATA_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/examples_new/orig_heights"

if ($SLURM_ARRAY_TASK_ID == 1) then
    python3 -u "${CODE_DIR_NAME}/explore_full_and_subset_data.py" \
    --input_example_file_names "${TOP_DATA_DIR_NAME}/training/learning_examples_2019_part01.nc" "${TOP_DATA_DIR_NAME}/training/learning_examples_2019_part02.nc" "${TOP_DATA_DIR_NAME}/training/learning_examples_2019_part03.nc" "${TOP_DATA_DIR_NAME}/training/learning_examples_2020_part01.nc" "${TOP_DATA_DIR_NAME}/training/learning_examples_2020_part02.nc" "${TOP_DATA_DIR_NAME}/training/learning_examples_2020_part03.nc" "${TOP_DATA_DIR_NAME}/validation/learning_examples_2020_part01.nc" "${TOP_DATA_DIR_NAME}/validation/learning_examples_2020_part02.nc" "${TOP_DATA_DIR_NAME}/validation/learning_examples_2020_part03.nc" "${TOP_DATA_DIR_NAME}/testing/learning_examples_2020_part01.nc" "${TOP_DATA_DIR_NAME}/testing/learning_examples_2020_part02.nc" "${TOP_DATA_DIR_NAME}/testing/learning_examples_2020_part03.nc" \
    --plot_shortwave=1 \
    --output_figure_dir_name="${TOP_DATA_DIR_NAME}/data_exploration/before_subsetting_for_tom"
else
    python3 -u "${CODE_DIR_NAME}/explore_full_and_subset_data.py" \
    --input_example_file_names "${TOP_DATA_DIR_NAME}/training/subset_for_tom/learning_examples_2020.nc" "${TOP_DATA_DIR_NAME}/validation/subset_for_tom/learning_examples_2020.nc" "${TOP_DATA_DIR_NAME}/testing/subset_for_tom/learning_examples_2020.nc" \
    --plot_shortwave=1 \
    --output_figure_dir_name="${TOP_DATA_DIR_NAME}/data_exploration/after_subsetting_for_tom"
endif
