#!/bin/tcsh

#SBATCH --job-name="write_100000ids_for_perm_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=write_100000ids_for_perm_test_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set INPUT_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/shortwave_examples_600days/orig_heights/normalized_not_flux/testing"
set OUTPUT_FILE_NAME="${INPUT_DIR_NAME}/example_ids_for_perm_test.nc"

python3 -u "${CODE_DIR_NAME}/write_random_example_ids.py" \
--input_example_dir_name="${INPUT_DIR_NAME}" \
--first_time_string="2017-01-01-000000" \
--last_time_string="2021-12-31-235959" \
--num_examples=100000 \
--output_id_file_name="${OUTPUT_FILE_NAME}"
