#!/bin/tcsh

#SBATCH --job-name="run_discard_test_for_heating_rates"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --array=1-63
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=run_discard_test_for_heating_rates_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_uq_experiment01"

set FIRST_LAYER_CHANNEL_COUNTS=("032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096")
set UQ_METHOD_STRINGS=("mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps")
set DENSE_LAYER_DROPOUT_RATES=("0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50")

set num_first_layer_channels=${FIRST_LAYER_CHANNEL_COUNTS[$SLURM_ARRAY_TASK_ID]}
set uq_method_string=${UQ_METHOD_STRINGS[$SLURM_ARRAY_TASK_ID]}
set dense_layer_dropout_rate=${DENSE_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/${uq_method_string}_num-first-layer-channels=${num_first_layer_channels}_dense-layer-dropout-rate=${dense_layer_dropout_rate}/model"
echo $model_dir_name

set prediction_file_name="${model_dir_name}/validation/predictions.nc"
set output_file_name="${model_dir_name}/validation/discard_test_for_heating_rates.nc"

python3 -u "${CODE_DIR_NAME}/run_discard_test.py" \
--input_prediction_file_name="${prediction_file_name}" \
--discard_fractions 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 \
--scaling_factor_for_dwmse=1 \
--scaling_factor_for_flux_mse=0 \
--use_hr_for_uncertainty=1 \
--output_file_name="${output_file_name}"

