#!/bin/tcsh

#SBATCH --job-name="plot_discard_test_for_heating_rates"
#SBATCH --partition="bigmem"
#SBATCH --account="gsd-hpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=02:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_discard_test_for_heating_rates_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment02"

set evaluation_dir_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/validation_perturbed_for_uq"

set PERTURBATION_TYPE_STRINGS_DASHED=("liquid-water-content-kg-m03" "ice-water-content-kg-m03" "specific-humidity-kg-kg01" "temperature-kelvins" "o3-mixing-ratio-kg-kg01")
set PERTURBATION_TYPE_STRINGS_UNDERSCORED=("liquid_water_content_kg_m03" "ice_water_content_kg_m03" "specific_humidity_kg_kg01" "temperature_kelvins" "o3_mixing_ratio_kg_kg01")

set i=1

while ($i <= ${#PERTURBATION_TYPE_STRINGS_DASHED})
    set perturbation_type_string_dashed=${PERTURBATION_TYPE_STRINGS_DASHED[$i]}
    set perturbation_type_string_underscored=${PERTURBATION_TYPE_STRINGS_UNDERSCORED[$i]}
    
    set input_file_name="${evaluation_dir_name}/by_perturbation_type/${perturbation_type_string_underscored}/discard_test_for_heating_rates.nc"
    set output_dir_name="${evaluation_dir_name}/by_perturbation_type/${perturbation_type_string_underscored}/discard_test_for_heating_rates"
    
    python3 -u "${CODE_DIR_NAME}/plot_discard_test.py" \
    --input_file_name="${input_file_name}" \
    --output_dir_name="${output_dir_name}"
    
    @ i = $i + 1
end
