#!/bin/bash

#SBATCH --job-name="convert_best_model_to_single_out_layer"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --array=0
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=convert_best_model_to_single_out_layer_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/spectral_experiment05lw_more_losses"

MIN_DUAL_WEIGHTS=("0.75")
BROADBAND_WEIGHTS=("0.01")
NORMALIZATION_TYPE_STRINGS=("new")

min_dual_weight=${MIN_DUAL_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
broadband_weight=${BROADBAND_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
normalization_type_string=${NORMALIZATION_TYPE_STRINGS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/min-dual-weight=${min_dual_weight}_broadband-weight=${broadband_weight}_normalization-type=${normalization_type_string}"

python3 -u "${CODE_DIR_NAME}/convert_model_to_single_output_layer.py" \
--input_keras_file_name="${model_dir_name}/model.keras" \
--output_tensorflow_dir_name="${model_dir_name}/model_with_single_output_layer"
