#!/bin/tcsh

#SBATCH --job-name="plot_large_error_frequencies"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
#SBATCH --array=29
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_large_error_frequencies_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_bnn_crps_experiment00"

FIRST_LAYER_CHANNEL_COUNTS=("064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128" "064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "064" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128" "128")
BAYESIAN_SKIP_LAYER_COUNTS=("1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2")
BAYESIAN_UPCONV_LAYER_COUNTS=("1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2")
BAYESIAN_DENSE_LAYER_COUNTS=("1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3" "1" "1" "2" "2" "3" "3")
BAYESIAN_LAYER_TYPE_STRINGS=("flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization" "flipout" "reparameterization")

model_dir_name="${TOP_MODEL_DIR_NAME}/num-first-layer-channels=${FIRST_LAYER_CHANNEL_COUNTS[$SLURM_ARRAY_TASK_ID]}_num-bayesian-skip-layers=${BAYESIAN_SKIP_LAYER_COUNTS[$SLURM_ARRAY_TASK_ID]}_num-bayesian-upconv-layers=${BAYESIAN_UPCONV_LAYER_COUNTS[$SLURM_ARRAY_TASK_ID]}_num-bayesian-dense-layers=${BAYESIAN_DENSE_LAYER_COUNTS[$SLURM_ARRAY_TASK_ID]}_bayesian-layer-type=${BAYESIAN_LAYER_TYPE_STRINGS[$SLURM_ARRAY_TASK_ID]}"

evaluation_dir_name="${model_dir_name}/model/validation_perturbed_for_uq/evaluation"
evaluation_file_name="${evaluation_dir_name}.nc"

python3 -u "${CODE_DIR_NAME}/plot_large_error_frequencies.py" \
--input_prediction_file_names "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part01.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part02.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part03.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part04.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part05.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part06.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part07.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part08.nc" "${model_dir_name}/model/validation_perturbed_for_uq/predictions_part09.nc" \
--large_hr_error_threshold_k_day01=1 \
--large_flux_error_threshold_w_m02=10 \
--catastrophic_error_confidence_threshold=0.95 \
--wavelengths_metres 1000 \
--output_dir_name="${evaluation_dir_name}"
