#!/bin/bash

#SBATCH --job-name="james2023_plot_perturbation_levels"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=james2023_plot_perturbation_levels_%A.out

module load imagemagick/7.1.1-11
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"

python3 -u "${CODE_DIR_NAME}/james2023_plot_perturbation_levels.py" \
--input_example_file_names "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/shortwave_examples_600days/orig_heights/training_all_perturbed_for_uq_small_unperturbed/learning_examples_2018_part01.nc" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/shortwave_examples_600days/orig_heights/training_all_perturbed_for_uq_small/learning_examples_2018_part01.nc" \
--file_description_strings "Clean" "Lightly_perturbed" \
--num_examples=200 \
--output_dir_name="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/james2023/perturbation_levels"
