#!/bin/tcsh

#SBATCH --job-name="apply_isotonic_regression"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_isotonic_regression_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/u-net++_test"

set neural_net_file_names={${MODEL_DIR_NAME}/model*.h5}
set neural_net_file_name=${neural_net_file_names[$#neural_net_file_names]}
set model_dir_name=`echo $neural_net_file_name | rev | cut -c 4- | rev`

set isotonic_model_dir_name="${model_dir_name}/isotonic_regression"
set isotonic_model_file_name="${isotonic_model_dir_name}/isotonic_regression.dill"

set orig_prediction_file_name="${model_dir_name}/validation_tropical_sites/predictions.nc"
set new_prediction_file_name="${isotonic_model_dir_name}/validation_tropical_sites/predictions.nc"

python3 -u "${CODE_DIR_NAME}/apply_isotonic_regression.py" \
--input_prediction_file_name="${orig_prediction_file_name}" \
--input_model_file_name="${isotonic_model_file_name}" \
--output_prediction_file_name="${new_prediction_file_name}"
