#!/bin/tcsh

#SBATCH --job-name="evaluate_by_site"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=02:00:00
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_site_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/u-net++_test"

set model_file_names={${MODEL_DIR_NAME}/model*.h5}
set model_file_name=${model_file_names[$#model_file_names]}
set model_dir_name=`echo $model_file_name | rev | cut -c 4- | rev`

set validation_dir_name="${model_dir_name}/isotonic_regression/validation_tropical_sites"
set prediction_file_names=("${validation_dir_name}/by_site/hilo_hi/predictions.nc" "${validation_dir_name}/by_site/honolulu_hi/predictions.nc" "${validation_dir_name}/by_site/guantanamo_bay/predictions.nc" "${validation_dir_name}/by_site/san_juan_pr/predictions.nc" "${validation_dir_name}/by_site/rohlsen_us_virgin_islands/predictions.nc" "${validation_dir_name}/by_site/bishop_grenada/predictions.nc" "${validation_dir_name}/by_site/perdido_oil_rig/predictions.nc")
set prediction_dir_names=("${validation_dir_name}/by_site/hilo_hi" "${validation_dir_name}/by_site/honolulu_hi" "${validation_dir_name}/by_site/guantanamo_bay" "${validation_dir_name}/by_site/san_juan_pr" "${validation_dir_name}/by_site/rohlsen_us_virgin_islands" "${validation_dir_name}/by_site/bishop_grenada" "${validation_dir_name}/by_site/perdido_oil_rig")

set i=1

while ($i <= ${#prediction_file_names})
    python3 -u "${CODE_DIR_NAME}/evaluate_neural_net.py" \
    --input_prediction_file_name="${prediction_file_names[$i]}" \
    --output_dir_name="${prediction_dir_names[$i]}"

    @ i = $i + 1
end
