#!/bin/tcsh

#SBATCH --job-name="run_discard_test_for_fluxes"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --array=1-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=run_discard_test_for_fluxes_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment01"

set PATHLESS_INPUT_FILE_NAMES=("predictions_part01.nc" "predictions_part02.nc" "predictions_part03.nc" "predictions_part04.nc" "predictions_part05.nc" "predictions_part06.nc" "predictions_part07.nc" "predictions_part08.nc" "predictions_part09.nc")
set PATHLESS_OUTPUT_FILE_NAMES=("discard_test_for_fluxes_part01.nc" "discard_test_for_fluxes_part02.nc" "discard_test_for_fluxes_part03.nc" "discard_test_for_fluxes_part04.nc" "discard_test_for_fluxes_part05.nc" "discard_test_for_fluxes_part06.nc" "discard_test_for_fluxes_part07.nc" "discard_test_for_fluxes_part08.nc" "discard_test_for_fluxes_part09.nc")

set prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_100x5/validation/${PATHLESS_INPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"
set output_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_100x5/validation/${PATHLESS_OUTPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/run_discard_test.py" \
--input_prediction_file_name="${prediction_file_name}" \
--discard_fractions 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 \
--scaling_factor_for_dwmse=0 \
--scaling_factor_for_flux_mse=1 \
--use_hr_for_uncertainty=0 \
--output_file_name="${output_file_name}"

