#!/bin/bash

#SBATCH --job-name="apply_isotonic_regression"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --array=1,2,4,6,7,8,9,12,13,14,17,18,19,24,25,30,31,34
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_isotonic_regression_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/spectral_experiment06_convnext_tweaks"

USE_CONVNEXT_V1_FLAGS=("1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0")
USE_CONVNEXT_V2_FLAGS=("0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1" "0" "0" "0" "1" "1" "1")
SIMPLIFY_CONVNEXT_FLAGS=("0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1")
SIMPLIFY_OUTPUT_FLAGS=("0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1")
OUTPUT_ACTIV_FUNCTIONS=("None" "None" "None" "None" "None" "None" "None" "None" "None" "None" "None" "None" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "relu" "None" "None" "None" "None" "None" "None" "None" "None" "None" "None" "None" "None")
OPTIMIZER_FUNCTION_DESCRIPTIONS=("basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay" "basic" "clipnorm" "smaller-weight-decay")

use_convnext_v1_flag=${USE_CONVNEXT_V1_FLAGS[$SLURM_ARRAY_TASK_ID]}
use_convnext_v2_flag=${USE_CONVNEXT_V2_FLAGS[$SLURM_ARRAY_TASK_ID]}
simplify_convnext_flag=${SIMPLIFY_CONVNEXT_FLAGS[$SLURM_ARRAY_TASK_ID]}
simplify_output_flag=${SIMPLIFY_OUTPUT_FLAGS[$SLURM_ARRAY_TASK_ID]}
output_activ_function=${OUTPUT_ACTIV_FUNCTIONS[$SLURM_ARRAY_TASK_ID]}
optimizer_function_description=${OPTIMIZER_FUNCTION_DESCRIPTIONS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/use-convnext-v1=${use_convnext_v1_flag}_use-convnext-v2=${use_convnext_v2_flag}_simplify-convnext=${simplify_convnext_flag}_simplify-output=${simplify_output_flag}_output-activation=${output_activ_function}_optimizer=${optimizer_function_description}"

isotonic_model_dir_name="${model_dir_name}/isotonic_regression"
isotonic_model_file_name="${isotonic_model_dir_name}/isotonic_regression.dill"
orig_prediction_file_name="${model_dir_name}/validation/predictions.nc"
new_prediction_file_name="${isotonic_model_dir_name}/validation/predictions.nc"

python3 -u "${CODE_DIR_NAME}/apply_isotonic_regression.py" \
--input_prediction_file_name="${orig_prediction_file_name}" \
--input_model_file_name="${isotonic_model_file_name}" \
--output_prediction_file_name="${new_prediction_file_name}"
