#!/bin/tcsh

#SBATCH --job-name="create_template_new"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=02:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=create_template_new_%A.out

singularity exec --nv /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/ml-ryan.simg /bin/sh -c "cp -v /scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/dense_variational.py /usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/layers/; cp -v /scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tccf_project/conv_variational.py /usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/layers/; cd /scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt/slurm/bnn_plusplus_test; sh create_template.sh"
