#!/bin/bash

#SBATCH --job-name="evaluate_models"
#SBATCH --partition="bigmem"
#SBATCH --account="gsd-hpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=06:00:00
#SBATCH --array=20-39
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_models_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/spectral_experiment05lw_more_losses"

MIN_DUAL_WEIGHTS=("0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00" "0.10" "0.25" "0.50" "0.75" "1.00")
BROADBAND_WEIGHTS=("0.01" "0.01" "0.01" "0.01" "0.01" "0.05" "0.05" "0.05" "0.05" "0.05" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.01" "0.01" "0.01" "0.01" "0.01" "0.05" "0.05" "0.05" "0.05" "0.05" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20")
NORMALIZATION_TYPE_STRINGS=("old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "old" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new" "new")

min_dual_weight=${MIN_DUAL_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
broadband_weight=${BROADBAND_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
normalization_type_string=${NORMALIZATION_TYPE_STRINGS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/min-dual-weight=${min_dual_weight}_broadband-weight=${broadband_weight}_normalization-type=${normalization_type_string}"
prediction_file_name="${model_dir_name}/isotonic_regression/validation/predictions.nc"
validation_dir_name="${model_dir_name}/isotonic_regression/validation/percentiles_instead_of_abs_values"

python3 -u "${CODE_DIR_NAME}/evaluate_neural_net.py" \
--input_prediction_file_name="${prediction_file_name}" \
--num_bootstrap_reps=1 \
--num_heating_rate_bins=81 \
--heating_rate_limits_percentile 0 100 \
--num_raw_flux_bins=45 \
--raw_flux_limits_percentile 0 100 \
--num_net_flux_bins=52 \
--net_flux_limits_percentile 0 100 \
--output_dir_name="${validation_dir_name}"
