#!/bin/bash

#SBATCH --job-name="apply_neural_nets"
#SBATCH --partition="bigmem"
#SBATCH --account="gsd-hpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --array=0
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/pareto2024_experiment/dense_net"
EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/examples_with_correct_vertical_coords/shortwave/normalized_predictors/testing"

FIRST_TESTING_TIME_STRING="2019-12-24-000000"
LAST_TESTING_TIME_STRING="2020-12-31-235959"

MODEL_DEPTHS=("1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "3" "3" "3" "3" "3" "3" "4" "4" "4" "4" "4" "4" "5" "5" "5" "5" "5" "5" "6" "6" "6" "6" "6" "6")
HIDDEN_LAYER_NEURON_COUNTS=("0064" "0128" "0256" "0512" "1024" "2048" "0064" "0128" "0256" "0512" "1024" "2048" "0064" "0128" "0256" "0512" "1024" "2048" "0064" "0128" "0256" "0512" "1024" "2048" "0064" "0128" "0256" "0512" "1024" "2048" "0064" "0128" "0256" "0512" "1024" "2048")

model_depth=${MODEL_DEPTHS[$SLURM_ARRAY_TASK_ID]}
num_hidden_layer_neurons=${HIDDEN_LAYER_NEURON_COUNTS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/num-levels=${model_depth}_num-neurons-per-layer=${num_hidden_layer_neurons}"
prediction_file_name="${model_dir_name}/testing/predictions.nc"

python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
--input_model_file_name="${model_file_name}" \
--input_example_dir_name="${EXAMPLE_DIR_NAME}" \
--first_time_string="${FIRST_TESTING_TIME_STRING}" \
--last_time_string="${LAST_TESTING_TIME_STRING}" \
--output_file_name="${prediction_file_name}"
