#!/bin/tcsh

#SBATCH --job-name="plot_pit_histograms_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --array=1-63
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_pit_histograms_test_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_uq_experiment01"

set FIRST_LAYER_CHANNEL_COUNTS=("032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096" "032" "032" "032" "032" "032" "032" "032" "064" "064" "064" "064" "064" "064" "064" "096" "096" "096" "096" "096" "096" "096")
set UQ_METHOD_STRINGS=("mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "mc-dropout" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps" "mc-crps")
set DENSE_LAYER_DROPOUT_RATES=("0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50" "0.01" "0.05" "0.10" "0.20" "0.30" "0.40" "0.50")

set num_first_layer_channels=${FIRST_LAYER_CHANNEL_COUNTS[$SLURM_ARRAY_TASK_ID]}
set uq_method_string=${UQ_METHOD_STRINGS[$SLURM_ARRAY_TASK_ID]}
set dense_layer_dropout_rate=${DENSE_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/${uq_method_string}_num-first-layer-channels=${num_first_layer_channels}_dense-layer-dropout-rate=${dense_layer_dropout_rate}/model"
echo $model_dir_name

set input_file_name="${model_dir_name}/testing_perturbed_for_uq/pit_histograms_20200118-20200131.nc"
set output_dir_name="${model_dir_name}/testing_perturbed_for_uq/pit_histograms_20200118-20200131"

python3 -u "${CODE_DIR_NAME}/plot_pit_histograms.py" \
--input_file_name="${input_file_name}" \
--output_dir_name="${output_dir_name}"
