#!/bin/tcsh

#SBATCH --job-name="evaluate_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --array=1-125%70
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_uq_experiment02"

set DENSE_LAYER_DROPOUT_RATES=("0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50")
set CONV_LAYER_DROPOUT_RATES=("0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.10" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.20" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.30" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.40" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50" "0.50")
set CONV_LAYERS_WITH_DROPOUT_COUNTS=("1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5" "1" "2" "3" "4" "5")

set dense_layer_dropout_rate=${DENSE_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set conv_layer_dropout_rate=${CONV_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set num_conv_layers_with_dropout=${CONV_LAYERS_WITH_DROPOUT_COUNTS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/dense-layer-dropout-rate=${dense_layer_dropout_rate}_conv-layer-dropout-rate=${conv_layer_dropout_rate}_num-conv-layers-with-dropout=${num_conv_layers_with_dropout}/model"
set prediction_file_name="${model_dir_name}/validation/predictions.nc"
set evaluation_dir_name="${model_dir_name}/validation"

python3 -u "${CODE_DIR_NAME}/evaluate_neural_net.py" \
--input_prediction_file_name="${prediction_file_name}" \
--num_bootstrap_reps=1 \
--num_heating_rate_bins=41 \
--heating_rate_limits_k_day01 0 41 \
--num_raw_flux_bins=50 \
--raw_flux_limits_w_m02 0 1250 \
--num_net_flux_bins=41 \
--net_flux_limits_w_m02 -1050 1000 \
--output_dir_name="${evaluation_dir_name}"
