#!/bin/tcsh

#SBATCH --job-name="subset_gfs_from_jebb_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=subset_gfs_from_jebb_test_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
set ATMOSPHERE_FILE_NAMES_STRING="/scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf006.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf012.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf018.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf024.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf030.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.atmf036.nc"
set SURFACE_FILE_NAMES_STRING="/scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf006.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf012.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf018.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf024.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf030.nc /scratch1/RDARCH/rda-ghpcs/Jebb.Q.Stewart/archive/ml_rt_fv3/20191201/gfs.20191201/00/gfs.t00z.sfcf036.nc"
set OUTPUT_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_project/gfs_data/gfs_init=2019-12-01-00.nc"

python3 -u "${CODE_DIR_NAME}/subset_gfs_from_jebb.py" \
--input_atmos_file_names ${ATMOSPHERE_FILE_NAMES_STRING} \
--input_surface_file_names ${SURFACE_FILE_NAMES_STRING} \
--site_rows 0 1 2 3 4 5 10 50 100 1000 \
--site_columns 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 \
--output_file_name="${OUTPUT_FILE_NAME}"
