#!/bin/tcsh

#SBATCH --job-name="make_calibration_schematic"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=make_calibration_schematic_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment02"

set base_prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/testing_perturbed_for_uq/predictions_part01.nc"
set isotonic_prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/isotonic_regression/testing_perturbed_for_uq/predictions_part01.nc"
set uncty_calibrated_prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/isotonic_regression/uncertainty_calibration/testing_perturbed_for_uq/predictions_part01.nc"
set output_dir_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/isotonic_regression/uncertainty_calibration/testing_perturbed_for_uq/calibration_schematics"

python3 -u "${CODE_DIR_NAME}/make_calibration_schematic.py" \
--input_base_prediction_file_name="${base_prediction_file_name}" \
--input_isotonic_prediction_file_name="${isotonic_prediction_file_name}" \
--input_uncty_calibrated_prediction_file_name="${uncty_calibrated_prediction_file_name}" \
--num_examples_to_plot=100 \
--output_dir_name="${output_dir_name}"
