#!/bin/tcsh

#SBATCH --job-name="make_pit_histograms"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --time=30:00:00
#SBATCH --array=1-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=make_pit_histograms_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone_sr/ml4rt"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment02"

set PATHLESS_INPUT_FILE_NAMES=("predictions_part01.nc" "predictions_part02.nc" "predictions_part03.nc" "predictions_part04.nc" "predictions_part05.nc" "predictions_part06.nc" "predictions_part07.nc" "predictions_part08.nc" "predictions_part09.nc")
set PATHLESS_OUTPUT_FILE_NAMES=("pit_histograms_part01.nc" "pit_histograms_part02.nc" "pit_histograms_part03.nc" "pit_histograms_part04.nc" "pit_histograms_part05.nc" "pit_histograms_part06.nc" "pit_histograms_part07.nc" "pit_histograms_part08.nc" "pit_histograms_part09.nc")

set prediction_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/isotonic_regression/uncertainty_calibration/testing_perturbed_for_uq/${PATHLESS_INPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"
set output_file_name="${TOP_MODEL_DIR_NAME}/multimodel_ensemble_50/isotonic_regression/uncertainty_calibration/testing_perturbed_for_uq/${PATHLESS_OUTPUT_FILE_NAMES[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/make_pit_histograms.py" \
--input_prediction_file_name="${prediction_file_name}" \
--num_bins=20 \
--output_file_name="${output_file_name}"
