#!/bin/bash

#SBATCH --job-name="make_model_comparison_fig_clean_validation_4models"
#SBATCH --partition="bigmem"
#SBATCH --account="gsd-hpcs"
#SBATCH --qos="urgent"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=make_model_comparison_fig_clean_validation_4models_%A.out

module load imagemagick/7.1.1-11
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"

python3 -u "${CODE_DIR_NAME}/james2023_make_model_comparison_figure.py" \
--input_model_evaluation_dir_names "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_crps_experiment00/model/validation_perturbed_for_uq" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_no_crps_experiment01/multimodel_ensemble_50x1/validation_perturbed_for_uq" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_mme_experiment01/multimodel_ensemble_50/validation_perturbed_for_uq" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_bnn_experiment00/num-first-layer-channels=064_num-bayesian-skip-layers=2_num-bayesian-upconv-layers=2_num-bayesian-dense-layers=3_bayesian-layer-type=reparameterization/model/validation_perturbed_for_uq" \
--model_description_strings "CRPS-only" "MME-only" "MME/CRPS" "BNN-only" \
--output_dir_name="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/shortwave_uq_comparison/clean_validation"
