#!/bin/bash

#SBATCH --job-name="convert_nn_and_ir_to_tensorflow_flat"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --array=0-9
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=convert_nn_and_ir_to_tensorflow_flat_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_standalone/ml4rt"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4rt_models/spectral_experiment07_longwave"

USE_RESIDUAL_FLAGS=("0" "0" "0" "0" "0" "1" "1" "1" "1" "1")
RANDOM_SEEDS=("0" "1" "2" "3" "4" "0" "1" "2" "3" "4")

use_residual_flag=${USE_RESIDUAL_FLAGS[$SLURM_ARRAY_TASK_ID]}
random_seed=${RANDOM_SEEDS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/use-residual=${use_residual_flag}_random-seed=${random_seed}"
input_nn_file_name="${model_dir_name}/model.weights.h5"
output_nn_dir_name="${model_dir_name}/tensorflow_model_flattened_output_no_ir"
iso_reg_file_name="${model_dir_name}/isotonic_regression/isotonic_regression.dill"

python3 -u "${CODE_DIR_NAME}/convert_nn_and_ir_to_tensorflow.py" \
--input_nn_file_name="${input_nn_file_name}" \
--input_iso_reg_file_name="" \
--flatten_output=1 \
--output_nn_dir_name="${output_nn_dir_name}"
